### ISSUE TITLE
How do I verify that a signature is signed by the address?

### ISSUE THREAD

**Issue by markibanez** [GemWallet/gemwallet-extension#120]
Hi,

Using your @gemwallet/api package, I am able to sign string messages. I'm not sure how I would validate this in my backend though? The same way I would with ethersjs on the ethereum side of things. I had a look at this repo https://github.com/XRPL-Labs/verify-xrpl-signature but it looks like it is not applicable here. 

Appreciate any help. Thank you.

**Comment by markibanez** [comment]
Nevermind, I found the solution

**Comment by FlorianBouron** [comment]
Hi @markibanez,
I've just seen your issue.
Yes you can do it like this: https://github.com/GemWallet/web3-auth-starter/blob/master/index.js#L40
