### ISSUE TITLE
getNetwork() API not working

### ISSUE THREAD

**Issue by florent-uzio** [GemWallet/gemwallet-extension#138]
Hello,

When I try to use the `getNetwork()` API, I get the following error in the console:

```
Unchecked runtime.lastError: The message port closed before a response was received.
```

![image](https://user-images.githubusercontent.com/36513774/232322464-77e7c771-8c7a-41f9-a832-5077b8774dd5.png)

The `isConnected()` API returns `true` but then impossible to get the network.

**Comment by FlorianBouron** [comment]
Hi Florent, I'll be looking into that, thanks for reporting it.

**Comment by FlorianBouron** [comment]
Hi @florent-uzio, I cannot reproduce your issue with the `getNetwork` not working, could you please share some code snippet in order that I try to reproduce your issue?

**Comment by florent-uzio** [comment]
Hi @FlorianBouron , you can check my repo, this line of code:

https://github.com/florent-uzio/xrpl-demo/blob/main/src/shared/contexts/gemwallet-connection-context.tsx#L29

You can uncomment the three lines (29, 30, 31).

Let me know if you see the same issue or if it works for you.

I am reading different articles about this error such as:
https://technolads.com/unchecked-runtime-lasterror-the-message-port-closed/

**Comment by FlorianBouron** [comment]
I do have the error message, it comes from the communication between the content script and the background script.
Though, I am getting the network.
Thank you for the code, let me try to reproduce it with your repository.

**Comment by FlorianBouron** [comment]
Hey @florent-uzio ,
I have it working, I have created an MR right here: https://github.com/florent-uzio/xrpl-demo/pull/1
We are investigating the error in the console though, it doesn't block the use of GemWallet.
Thank you so much for your bug report.

**Comment by FlorianBouron** [comment]
@all-contributors please add @florent-uzio for bug

**Comment by FlorianBouron** [comment]
If the getNetwork works for you, feel free to close the issue :)

**Comment by florent-uzio** [comment]
Sure, I will work on it a bit more today as I want to update regularly the network in the context in case for some reason the user changes the network in GemWallet while my app is open.
If that works fine I will close this issue :)

**Comment by florent-uzio** [comment]
I can get the network with `getNetwork()` but the error message still appears in the console:

```
Unchecked runtime.lastError: The message port closed before a response was received.
```

I will close this issue as the api is working but it might be good to fix the error message in the console in the future :)

**Comment by FlorianBouron** [comment]
Thank you really appreciate it, we will be taking a look at it right after we are done with our next release.
Thank you so much for raising the issue.
