### ISSUE TITLE
Extension requires password on every interaction

### ISSUE THREAD

**Issue by rikublock** [GemWallet/gemwallet-extension#178]
Issue #121 didn't quiet solve the problem in my case. 
The wallet extension app still prompts the user for a password on **every** interaction.
- when opening the wallet via UI icon in the browser 
- when making requests via API

Setup:
- Chromium Version 113.0.5672.126
- Ubuntu 22.04 (64-bit)

**Comment by FlorianBouron** [comment]
Hi @rikublock,
Thank you, we are gonna work on it.

**Comment by FlorianBouron** [comment]
Issue is now moved to `IN PROGRESS`

**Comment by rikublock** [comment]
> Issue is now moved to `IN PROGRESS`

Great. Were you able to reproduce it ? Let me know, if you need more details.

**Comment by FlorianBouron** [comment]
Yes, I was able to reproduce it, it's my priority ticket.

**Comment by ThibautBremand** [comment]
Hello @rikublock , the feature has been released to the Chrome store 👍
Now you will have 30 minutes sessions when you check the box on the login page.

**Comment by rikublock** [comment]
> Hello @rikublock , the feature has been released to the Chrome store +1 Now you will have a 30 minutes session when you check the box on the login page.

That did resolve my problems. Here some minor remarks:

- Personally, I find the unlock checkbox a bit annoying and would prefer, if the wallet just unlocks for a certain amount of time. I guess I'm just used to that behavior, because most other wallets do it that way (e.g. Metamask, WalletConnect, etc.). Could be nice to at least remember the previous checkbox setting.

- It would be helpful to have an `IsLocked(): boolean` API to quickly check, if the extension is currently locked without creating any popup windows. If you like, I could probably throw a PR  together for this.

**That's sort of the use case that started the initial issue:**
Restore web app state after page refresh (e.g. load current address and network). However, we would want to avoid poping up extension windows without explicit user interaction at all cost (bad UX). If the wallet is currently unlock, we can request that information, otherwise no.

**Comment by ThibautBremand** [comment]
Hello @rikublock , we have released a new version to the Chrome store. Now on login, the extension remembers the previous setting of the 30 minutes session checkbox. 👍
