### ISSUE TITLE
[feat] Events to notify web app about state changes

### ISSUE THREAD

**Issue by rikublock** [GemWallet/gemwallet-extension#179]
Add an event system that allows web apps to react to extension state changes. It's currently quite difficult to stay in sync with what is happening with the extension without constantly polling the state.
Possibly something based on Node.js [EventEmitter](https://nodejs.org/api/events.html).

Example:
- **networkChanged**:  switch from "devnet" to "testnet"
- **walletChanged / accountChanged**: selected new active wallet
- **login, logout**: extension locked or unlocked
- etc.

Usage:
```js
GemWalletApi.on('networkChanged', (network: string) => {
  console.log(`New network: ${network}`);
});
```

**Comment by FlorianBouron** [comment]
Hi @rikublock,
That's a really good feedback, let us working on it in our next releases.
Thank you so much for your feedbacks.

**Comment by FlorianBouron** [comment]
@all-contributors add @rikublock for bug and ideas

**Comment by FlorianBouron** [comment]
Hi @rikublock, just to let you know that the change got merged to master, thanks for the suggestion.
We will be planning a release pretty soon to make the changes live.

**Comment by rikublock** [comment]
> Hi @rikublock, just to let you know that the change got merged to master, thanks for the suggestion. We will be planning a release pretty soon to make the changes live.

Cheers. Will give it a try once the docs are updated.

**Comment by FlorianBouron** [comment]
Hi @rikublock,
The doc has been updated.

**Comment by rikublock** [comment]
@FlorianBouron @ThibautBremand Got to say. You guys keep pushing these changes so quickly. I'm just amazed! Keep up the good work.

**Comment by ThibautBremand** [comment]
@rikublock Thank you! :)
