### ISSUE TITLE
cannot modify the wallet name if too long

### ISSUE THREAD

**Issue by tfevre** [GemWallet/gemwallet-extension#187]
![image](https://github.com/GemWallet/gemwallet-extension/assets/114390906/bce90854-2c77-4918-b982-006e85150b63)

I change the name of my "wallet 1" to my public address
Then, I can't update another time the name of my wallet because it is too long like you can see on the image

**Comment by FlorianBouron** [comment]
Hi @tfevre,
Thank you for your feedback, we are going to fix it ASAP in our next release

**Comment by FlorianBouron** [comment]
@all-contributors add @rikublock for bug

**Comment by FlorianBouron** [comment]
@all-contributors add @tfevre for bug

**Comment by FlorianBouron** [comment]
Resolved with https://github.com/GemWallet/gemwallet-extension/pull/189, it will be shipped with the next release

**Comment by FlorianBouron** [comment]
Resolved with https://github.com/GemWallet/gemwallet-extension/pull/189, it will be shipped with the next release
