### ISSUE TITLE
[Feat] Allowing developers to specify custom network

### ISSUE THREAD

**Issue by garantor** [GemWallet/gemwallet-extension#195]
Currently, GemWallet only supports the **mainnet**, **testnet**, **devnet**, and **Amm** network. This means that developers who want to interact with the XRPL must use one of these four networks. However, there are times when developers may want to test or interact with a custom network on the XRPL. It would be helpful to be able to specify a **custom network.**

**Comment by FlorianBouron** [comment]
Thank you for the recommendation, we are on it

**Comment by FlorianBouron** [comment]
@all-contributors add @garantor  for ideas

**Comment by ThibautBremand** [comment]
Hey @garantor , we have just merged the custom network feature on the master branch. It will be part of the next release.
Thank you for the feedback 👍

**Comment by garantor** [comment]
this is great @ThibautBremand!, i will be testing it soon

**Comment by garantor** [comment]
After adding a custom network, I decided to check it out. However, I noticed that when I switched from the dashboard tab of the extension to the transaction tab, the network changed back to my previously selected one. See video attach


https://vimeo.com/846914083?share=copy

**Comment by ThibautBremand** [comment]
Hey, thanks for the video, it looks like this behavior occurs when connected to a wss that is non XRPL. We are looking into it 👍

**Comment by ThibautBremand** [comment]
@all-contributors add @garantor for bug

**Comment by ThibautBremand** [comment]
Hey @garantor , we have merged a fix to master:  
When you fail to connect to a server, you will have an info dialog saying "Failed to connect to the network, you have been switched back to the previous network"

**Comment by ThibautBremand** [comment]
Hello @garantor , the feature has been released to the chrome store 👍

**Comment by garantor** [comment]
Hello @ThibautBremand, I just checked it out, and it worked perfectly. Great job! Also, thank you for adding the 30-minute unlocked screen feature; it's much appreciated.
