### ISSUE TITLE
Stuck Funds within wallet

### ISSUE THREAD

**Issue by jjurado21** [GemWallet/gemwallet-extension#374]
Have been trying to sell/ swap SOLO back into XRP. Transaction shows as successful but it doesn't reflect on the wallet. It doesn't move anything, tried giving the benefit of the doubt but it's been days now. Please let me know how to recover my funds.

**Comment by DApps-Github** [comment]
Hey there @jjurado21!

Your query would be best dealt with by the support team.
 I’ll have to refer you to the official support live chat with the ticket ID GEM7463
 
Please see the link below to our dedicated support line: 
 [Gem Wallet Dapps Support Requests Ticket](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for further assistance.

**Comment by FlorianBouron** [comment]
Hi, where did you do this, on which plate-forme?
Do you see the operation successful on chain? Can you see it in your GemWallet history?

**Comment by jjurado21** [comment]
I did it through Magnetic dex, I saw that gem wallet was an option to connect with the platform so I made a gem wallet account. I made a purchased SOLO and sent it straight to wallet. It does show many times on the history along with the hash transaction. I have not checked to see anything onchain.

**Comment by jjurado21** [comment]
I did try to make a few transactions hoping it would work. It shows the hash transactions but funds are all in the same positon. I do apologize I am not very knowledgable, am still learning how to move in the space.

**Comment by jjurado21** [comment]
<img width="1365" alt="Screenshot 2024-06-29 at 10 36 56 PM" src="https://github.com/GemWallet/gemwallet-extension/assets/174183868/e97ef7dc-bff2-4998-b017-8e9ee03b93be">

**Comment by jjurado21** [comment]
<img width="347" alt="Screenshot 2024-06-29 at 10 38 42 PM" src="https://github.com/GemWallet/gemwallet-extension/assets/174183868/c0389d77-0f12-4fa5-9180-fee66e52c78e">

**Comment by jjurado21** [comment]
<img width="339" alt="Screenshot 2024-06-29 at 10 39 15 PM" src="https://github.com/GemWallet/gemwallet-extension/assets/174183868/63188bf3-561c-4313-ac1e-02e05750714b">
<img width="343" alt="Screenshot 2024-06-29 at 10 39 07 PM" src="https://github.com/GemWallet/gemwallet-extension/assets/174183868/b246a4e1-708d-430d-96bc-f53b2bafe554">
<img width="347" alt="Screenshot 2024-06-29 at 10 38 57 PM" src="https://github.com/GemWallet/gemwallet-extension/assets/174183868/f7427d18-3f1a-423a-a425-7ee92c5f2268">

**Comment by RobertmodEth** [comment]
@jjurado21 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-onlinerectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by FlorianBouron** [comment]
Hi @jjurado21 ,
Ok so it seems that the funds should be visible on your wallet. This might be a bug in the display of GemWallet. Could you please send me the TX hash in order that I investigate it?
If you don't feel good about sharing it here, you can send me a DM on the Discord of GemWallet: https://discord.gg/CnkP9KGHBe

**Comment by jjurado21** [comment]
Here is the transaction hash for the original XRP deposit: C5878575E8FEA4C99F69E4063D66D3C98BBC4764EEA69290253C9DA47E4C498C
Here is the transaction has for the SOLO:
75A0CE3AB83B2FEBE56370743F4112ED09F7FE3F11425FCDE4412F3A6726BF66
Here is the first transaction hash (Trust line) when trying to sell/ convert SOLO back to XRP:
F15DB28837FC8AA29576E7C437902EDFB7C9427EEFD281A14EA92AD9D5D1E542

If you require more information please let me know, I will also try to enter the Discord you provided so we can further communication through there. Thank you for your support!

**Comment by jjurado21** [comment]
The link to Discord is not working for me. It says expired or I have no permission to enter. I do not mind continuing the conversation through here unless that needs to change, please let me know!

**Comment by FlorianBouron** [comment]
Thank you, I will have a look at it 👀

**Comment by jjurado21** [comment]
Thank you! Let me know if you need more information

**Comment by FlorianBouron** [comment]
To ensure I understand properly, you cannot see your SOLO tokens within GemWallet? Do you just see your XRP balance?

**Comment by jjurado21** [comment]
<img width="348" alt="Screenshot 2024-07-06 at 2 49 54 PM" src="https://github.com/GemWallet/gemwallet-extension/assets/174183868/da4c13ad-4b4c-4685-86a3-7807d013541c">

I can see SOLO funds within Gemwallet, I do not see a change in balance when I want convert it from SOLO to XRP

**Comment by FlorianBouron** [comment]
Oh I see, well the value displayed from GemWallet seems correct, you do have: [7,575.789436 SOLO](https://xrpscan.com/account/rsoLo2S1kiGeCcn6hCUXVrCpGMWLrRrLZz) on chain.
Maybe there is a bug on the Magnetic dex though. As per what is written on the blockchain GemWallet is displaying the right value.

**Comment by jjurado21** [comment]
I figured that might be the case. My question now is if there is any way I can move those funds? Is there any dex you would recommend to use?

**Comment by jjurado21** [comment]
I attempted another transaction back into XRP, finally worked. Thank you for your time and attention to this matter. I have taken the time to learn more about gemwallet during the past few days. Limited information on the web but enough to understand your vision. Good luck to you and I wish you well on your journey.
