### ISSUE TITLE
ACCOUNT NOT ACTIVATED

### ISSUE THREAD

**Issue by pilikan33** [GemWallet/gemwallet-extension#399]
ACCOUNT NOT ACTIVATED

To create this account to the XRP ledger, you will have to make a first deposit of a minimum 1 XRP.
[Learn more about the account reserve.](https://xrpl.org/reserves.html?utm_source=gemwallet.app)
Your reserved XRP will not show up within your GemWallet's balance as you cannot spend it.

But this is import Family Seed Secret - why ?
but there's a balance and the account is activated.

**Comment by Hinted-tech** [comment]
> ACCOUNT NOT ACTIVATED
> 
> To create this account to the XRP ledger, you will have to make a first deposit of a minimum 1 XRP. [Learn more about the account reserve.](https://xrpl.org/reserves.html?utm_source=gemwallet.app) Your reserved XRP will not show up within your GemWallet's balance as you cannot spend it.
> 
> But this is import Family Seed Secret - why ? but there's a balance and the account is activated.

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Gemwallet Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by pilikan33** [comment]
All ok
